### ISSUE TITLE
Can I use TerraCraft for a project?

### ISSUE THREAD

**Issue by ghost** [XenonCoder/PyCraft#52]
Hi,
I found this handsome project a few weeks ago and started messing around with the code.

I found it very useful and I want to work on a project using it as a code base (but I will also rewrite most of the engins)

Is it okay if I use it?

**Comment by benmoran56** [comment]
This is a GPL3 licensed project, so you can use it if you have a compatible free software license.

**Comment by ghost** [comment]
Alright thank you for your response.
